<div id="popup-modal-track" style="display: none;">
    <div id="popup-modal-track-mapa">

    </div>
    <div id="popup-modal-track-labels">

        <table>
            <tr class="rowlabel-track">
                <td class="rowlabel-track-first">Estado de la orden:</td><td class="rowlabel-track-value" id="trackingorden"></td>
            </tr>
            <tr class="rowlabel-track rowlabel-track-s">
                <td class="rowlabel-track-first">Ubicación actual de la entrega:</td><td class="rowlabel-track-value" id="trackingactual"></td>
            </tr>
            <tr class="rowlabel-track">
                <td class="rowlabel-track-first">Dirección Destino:</td><td class="rowlabel-track-value" id="trackingdestino"></td>
            </tr>
            <tr class="rowlabel-track rowlabel-track-s">
                <td class="rowlabel-track-first">Tiempo estimado:</td><td class="rowlabel-track-value" id="trackingtiempo"></td>
            </tr>
            <tr class="rowlabel-track">
                <td class="rowlabel-track-first">Distancia:</td><td class="rowlabel-track-value" id="trackingdistancia"></td>
            </tr>
        </table>

    </div>
</div>

<script type="text/javascript">

	require(
    [
        'jquery',
        'ko',
        'Magento_Ui/js/modal/modal'
    ],
    function(
        $,
        ko,
        modal
    ) {

        var map = null;
        var marker1 = null;
        var route = null;

        var destinolat = null;
        var destinolng = null;

        var actuallat = null;
        var actuallng = null;

        var directionDisplay = null;
        var directionsService;

        var imagen='';

        $(document).ready(function(){
            var key = "<?= $block->key() ?>";
            $.getScript("https://maps.googleapis.com/maps/api/js?v=3&sensor=false&key="+key, function () {     
                initialize();
            });

            function initialize(){

                directionsService =new google.maps.DirectionsService();
                directionsDisplay =new google.maps.DirectionsRenderer();

                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    size: 'sm',
                    title: '',
                    modalClass: 'modalMapa'
                };
                var popup = modal(options, $('#popup-modal-track'));

                jQuery(".trackingchazkiclick").click(function(){

                    var lataux = $(this).data("lat");
                    var lngaux = $(this).data("lng");
                        
                    $.get( window.checkout.baseUrl+"rest/V1/ChazkiDelivery",{orden:$(this).data("id")} ,function( data ) {
                        
                        if(data[0].response == 1){
                        	if(data[0].status=="Entregado"){
                        		alert("Ya se entrego el producto");
                        	}else if(data[0].status=="Fallo Entrega"){
                        		alert("Fallo Entrega: "+data[0].motivo);
                        	}else{
	                            imagen = '<?= $this->getViewFileUrl('VexShipping_Chazki::image/scooter.png') ?>';
	                            jQuery("#trackingorden").html(data[0].status);
	                            jQuery('#popup-modal-track').modal('openModal');
	                            setTimeout(function(){

	                                destinolat = parseFloat(data[0].destino.latitude);
	                                destinolng = parseFloat(data[0].destino.longitude);

	                                actuallat = parseFloat(data[0].position.latitude);
	                                actuallng = parseFloat(data[0].position.longitude);

	                                let uluru1 = {lat: actuallat, lng: actuallng};
	                                let uluru2 = {lat: destinolat, lng: destinolng};
	                                map = new google.maps.Map(document.getElementById('popup-modal-track-mapa'), {
	                                  zoom: 11,
	                                  center: uluru1
	                                });
	                                
	                                actmapa({lat: actuallat,lng:actuallng});

	                            },1000);
	                        }
                        }else{
                        	if(data.status!=null){
                        		alert(data[0].status)
                        	}else{
                        		alert("No se encontraron datos de la orden.")
                        	}
                        }
                    },'json');
                        
                });
                
                function actmapa(coords){

                    actuallat = coords.lat;
                    actuallng = coords.lng;

                    var request ={
                        origin:{lat:actuallat,lng:actuallng},
                        destination:{lat:destinolat,lng:destinolng},
                        travelMode: google.maps.TravelMode.DRIVING
                    };
                    
                    directionsService.route(request,function(result, status){
                        
                        if(status == google.maps.DirectionsStatus.OK){

                            if(directionDisplay!=null){
                                directionDisplay.setMap(null);
                            }
                            if(marker1!=null){
                                marker1.setMap(null);
                            }
                            directionDisplay = new google.maps.DirectionsRenderer({
                                map: map,
                                directions: result,
                                suppressMarkers: true
                            });

                            

                            var leg = result.routes[0].legs[0];
                            makeMarker(leg.start_location);
                            makeMarker2(leg.end_location);

                        }
                    });

                    calcularkm();
                }
                function makeMarker(position) {
                    let icon = new google.maps.MarkerImage(
                        imagen,
                        new google.maps.Size(64, 64),
                        new google.maps.Point(0, 0),
                        new google.maps.Point(22, 32)
                    )
                    marker1 = new google.maps.Marker({
                        position: position,
                        map: map,
                        icon: icon
                    });
                }
                function makeMarker2(position) {
                    new google.maps.Marker({
                        position: position,
                        map: map
                    });
                }
                function calcularkm(){
                    var service = new google.maps.DistanceMatrixService();
                    service.getDistanceMatrix(
                      {
                        origins: [{lat: actuallat, lng: actuallng}],
                        destinations: [{lat: destinolat, lng: destinolng}],
                        travelMode: 'DRIVING',
                        unitSystem: google.maps.UnitSystem.METRIC,
                        avoidHighways: true,
                        avoidTolls: true,
                      }, callback);
                }
                function callback(response, status) {
                    console.log(response)
                    if(status == 'OK'){
                        $("#trackingdestino").html(response.destinationAddresses[0]);
                        $("#trackingactual").html(response.originAddresses[0]);

                        if(response.rows[0].elements[0].status=='OK'){
                            $("#trackingdistancia").html(response.rows[0].elements[0].distance.text);
                            $("#trackingtiempo").html(response.rows[0].elements[0].duration.text);
                        }else{
                            $("#trackingdistancia").html("");
                            $("#trackingtiempo").html("");
                        }
                    }         
                }
            }

        });
    }
);

</script>