<?php $d = $block->getOrder();
	$datos = $d->getData();
	$id = $datos['entity_id'];
	$metodo = $datos['shipping_method'];
	$customer = $datos['customer_id'];
?>
<td data-th="<?php echo $this->escapeHtml(__('chaski')) ?>" class="col actions">
	<?php if($metodo == 'chazki_chazki') { ?>
	<a href="#" data-id="<?= $id ?>" data-cliente="<?= $customer ?>" class="trackingclick">Ver pedido</a>
	<?php } ?>
</td>